FROM python:3.8.10 

WORKDIR /.
COPY . .
RUN pip install -r ./project/requirements/requirements.txt  --upgrade pip
EXPOSE 3000
RUN export ENV=development
RUN export FLASK_DEBUG=development
CMD ["gunicorn","-w 4","-b 0.0.0.0:3000","--reload","-e ENV=development","main:app"]

