version: 2.1   

jobs:
  build:
    machine:
      image: ubuntu-2004:current 
    steps:
      - checkout
      - run: 
          name: 'Creating Docker image'
          command: docker build -t duftcola/app_template:latest .
      - run:
          name: 'Running docker image'
          command: docker run -d -p 3000:3000 -e CI=true --name app_template_container  duftcola/app_template
      - run:
          name: 'Testing'
          command: docker exec -it app_template_container pytest tests/