name: Testing app_template module 

on:
    push:
        branches: ["develop"]
jobs:
  testing:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Moving test images docker/testing --> .
          run: mv docker/development/.dockerignore . ; mv docker/development/dockerfile .
        - name: Build
          run: docker build -t duftcola/development .
        - name: Moving development image back . ---> docker/development
          run: mv .dockerignore docker/development/.dockerignore ; mv dockerfile docker/production/dockerfile
        - name: Running docker image
          run: docker run -d -p 3000:3000 -e CI=true -e ENV=testing --name duftcola_development_container duftcola/development 
        - name: Executing tests
          run: docker exec -e ENV=testing duftcola_development_container pytest ./project/tests
