name: Production ready 

on:
    pull_request:
        branches: ["master"]
jobs:
  clean_up:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Delete tests 1
          run: rm ./project/tests/test_app_example.py
        - name: Delete tests 2
          run: rm ./project/tests/test_app_validator.py
        - name: Delete tests 3
          run: rm ./project/tests/status_codes.py

        