name: Testing app_template module 

on:
    push:
        branches: ["develop"]
jobs:
  testing:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build
          run: docker build -t duftcola/app_template .
        - name: Running docker image
          run: docker run -d -p 3000:3000 -e CI=true --name app_template_container duftcola/app_template 
        - name: Executing tests
          run: docker exec app_template_container pytest tests/
