name: Testing app_template module 

on:
    push:
        branches: ["develop"]
jobs:
  testing:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Moving test images docker/testing --> .
        - run: mv docker/production/.dockerignore . ; mv docker/production/dockerfile .
        - name: Build
          run: docker build -t duftcola/testing .
        - name: Moving test images back . ---> docker/testing
          run: mv .dockerignore docker/production/ ; mv dockerfile docker/production/
        - name: Running docker image
          run: docker run -d -p 3000:3000 -e CI=true --name duftcola_testing duftcola/testing 
        - name: Executing tests
          run: docker exec app_template_container pytest app/tests/
